name: my-input-greet
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Type your name"
        required: true
        default: "Anonymous"

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Print data
        run: echo "Input name: ${{ github.event.inputs.name }}"
