name: my-first23
on:
  Push:
    branches:
       - main
workflow-dispatch:
inputs:
  name: "type your name"
jobs:
    greetings:
    runs-on: ubuntu-latest
    steps:
        name: printdata
        run echo " input guy" $ {{ github.event.inputs.name }}:
     
