name: my-first23
on:
  Push:
    branches:
       - main
workflow-dispatch:
inputs:
  name: "type your name"
jobs:
  greetings:
   runs-on: ubuntu-latest
     steps:
        echo " input guy" $ {{ github.event.name }}
     
